title: Marco Montagna, MD - AI in Medicine
description: Bridging the gap between AI and Medicine
baseurl: "" # Leave empty for GitHub Pages
url: "https://montagnam.github.io" # Replace with your GitHub Pages URL

theme: minima # Jekyll's built-in theme
markdown: kramdown

# Optional metadata
author: Marco Montagna, MD
email: montagna.marco@hsr.it